

global:
  scrape_interval: 15s

  evaluation_interval: 15s


scrape_configs:


  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'application-service'
    static_configs:
      - targets: ['host.docker.internal:3004']

  
  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:3000']

  
  - job_name: 'company-service'
    static_configs:
      - targets: ['host.docker.internal:3001']

  
  - job_name: 'job-service'
    static_configs:
      - targets: ['host.docker.internal:3002']

  
  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:4005']

  
  - job_name: 'chat-service'
    static_configs:
      - targets: ['host.docker.internal:4007']

  
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:4000']

